dist: bionic
addons:
  apt:
    packages:
    - bc 
    - bison
    - build-essential
    - ccache
    - curl 
    - flex 
    - g++-multilib 
    - gcc-multilib 
    - git 
    - gnupg 
    - gperf 
    - imagemagick 
    - lib32ncurses5-dev 
    - lib32readline-dev 
    - lib32z1-dev 
    - liblz4-tool 
    - libncurses5 
    - libncurses5-dev 
    - libsdl1.2-dev
    - libssl-dev 
    - libwxgtk3.0-dev
    - libxml2 
    - libxml2-utils 
    - lzop
    - pngcrush
    - python3
    - rsync 
    - schedtool 
    - squashfs-tools 
    - xsltproc 
    - zip 
    - zlib1g-dev 
    
install:
  - curl -s https://storage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo && chmod +x /usr/bin/repo
