language: c
os: linux
dist: bionic
addons:
  apt:
    packages:
    - bc 
    - bison
    - build-essential
    - ccache
    - curl 
    - flex 
    - g++-multilib 
    - gcc-multilib 
    - git 
    - gnupg 
    - gperf 
    - imagemagick 
    - lib32ncurses5-dev 
    - lib32readline-dev 
    - lib32z1-dev 
    - liblz4-tool 
    - libncurses5 
    - libncurses5-dev 
    - libsdl1.2-dev
    - libssl-dev 
    - libwxgtk3.0-dev
    - libxml2 
    - libxml2-utils 
    - lzop
    - pngcrush
    - python3
    - rsync 
    - schedtool 
    - squashfs-tools 
    - xsltproc 
    - zip 
    - zlib1g-dev 
    
install:
  - curl -s https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/null && sudo chmod +x /usr/bin/repo

before_script:
  - mkdir los
  - cd los
  - repo init -u https://github.com/LineageOS/android.git -b lineage-18.1
  - repo sync -j16
  - git clone https://gitlab.com/the-muppets/proprietary_vendor_xiaomi.git vendor/xiaomi
  - source build/envsetup.sh
  - breakfast vince

script:
  - cd los
  - source build/envsetup.sh
  - brunch vince
