version: '{build}'
skip_tags: true
image: Ubuntu1804
platform: x64
init:
- sh: >-
    sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq < /dev/null > /dev/null
    
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev python3 < /dev/null > /dev/null
    
    curl -s https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/null
    
    sudo chmod +x /usr/bin/repo
    
    sudo ln -sf /usr/bin/python3 /usr/bin/python
    
    git config --global user.email "1156393759@qq.com"
    
    git config --global user.name "gamecss@bot"
install:
- sh: >-
    mkdir /home/appveyor/projects/vince-build/los
    
    cd /home/appveyor/projects/vince-build/los
    
    repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-18.1
    
    repo sync -c -f --no-tags --no-clone-bundle -j16
    
    git clone https://gitlab.com/the-muppets/proprietary_vendor_xiaomi.git vendor/xiaomi
    
    source build/envsetup.sh
    
    breakfast vince
    
    rm -rf hardware/qcom-caf/wlan
    
    git clone --single-branch -b android11-release --depth 1 https://android.googlesource.com/platform/hardware/qcom/wlan hardware/qcom-caf/wlan
    
    rm -rf kernel/xiaomi/msm8953
    
    git clone  --single-branch -b darky --depth 1 https://github.com/Blacksuan19/kernel_dark_ages_vince.gitkernel/xiaomi/msm8953
    
    sed -i 's#TARGET_KERNEL_SOURCE := kernel/xiaomi/msm8953#\nTARGET_KERNEL_VERSION := 4.9' device/xiaomi/msm8953-common/BoardConfigCommon.mk

build_script:
- sh: >-
    source /home/appveyor/projects/vince-build/los/build/envsetup.sh
    
    croot
    
    brunch vince
