name: Compile lineageos of vince
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      USE_CCACHE: "1"
      CCACHE_EXEC: "/usr/bin/ccache"
    steps:
      - name: Configure
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/null
          sudo chmod +x /usr/bin/repo
          sudo apt install -yq bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev python3
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          git config --global user.email "1156393759@qq.com"
          git config --global user.name "gamecss@bot"
          mkdir ~/los
          cd ~/los
          repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-18.1
      - name: Get source
        run: |
          cd ~/los
          repo sync -c -f --no-tags --no-clone-bundle -j16
      - name: Setup device
        run: |
          cd ~/los
          git clone --single-branch -b lineage-18.1 --depth 1 https://gitlab.com/the-muppets/proprietary_vendor_xiaomi.git vendor/xiaomi
          source build/envsetup.sh
          breakfast vince
          rm -rf hardware/qcom-caf/wlan
          git clone https://android.googlesource.com/platform/hardware/qcom/wlan hardware/qcom-caf/wlan
          rm -rf kernel/xiaomi/msm8953
          git clone https://github.com/Blacksuan19/kernel_dark_ages_vince.git --single-branch -b darky kernel/xiaomi/msm8953
          sed -i 's#TARGET_KERNEL_SOURCE := kernel/xiaomi/msm8953#\nTARGET_KERNEL_VERSION := 4.9' device/xiaomi/msm8953-common/BoardConfigCommon.mk
      - name: Build
        run: |
          cd ~/los
          source build/envsetup.sh
          croot
          brunch vince
  sign:
    runs-on: ubuntu-18.04
    steps:
      - run: sleep 5
