name: Compile lineageos of vince
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      USE_CCACHE: "1"
      CCACHE_EXEC: "/usr/bin/ccache"
      BUILD_ENFORCE_SELINUX: "1"
      CPU_SSE42: "false"
    steps:
      - name: Configure
        run: |
          sudo curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo
          sudo chmod +x /usr/bin/repo
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev python3
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          git config --global user.email "1156393759@qq.com"
          git config --global user.name "gamecss@bot"
          ccache -M 50G
          mkdir /los
      - name: Get source
        run: |
          cd /los
          repo init -u https://github.com/LineageOS/android.git -b lineage-18.1
          repo sync
          git clone https://gitlab.com/the-muppets/proprietary_vendor_xiaomi.git vendor/xiaomi
          source build/envsetup.sh
          breakfast vince
      - name: Build
        run: |
          cd /los
          source build/envsetup.sh
          croot
          brunch vince
  sign:
    runs-on: ubuntu-18.04
    steps:
      - run: sleep 5
